config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"

  resources :jobs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to root_path
  end

  private
    def job_params
      params.require(:job).permit(:title, :company, :salary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with model: job, class: "form" do |form| %>
  <div class="mb-3">
    <div class="form-floating">
      <%= form.text_field :title, class: "form-control", required: "required", placeholder: "Job title" %>
      <%= form.label :title, class: "control-label" %>
      <% job.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <div class="form-floating">
      <%= form.text_field :company, class: "form-control", required: "required", placeholder: "Job company" %>
      <%= form.label :company, class: "control-label" %>
      <% job.errors.full_messages_for(:company).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <div class="form-floating">
      <%= form.number_field :salary, class: "form-control", required: "required", placeholder: "Position salary" %>
      <%= form.label :salary, class: "control-label" %>
      <% job.errors.full_messages_for(:salary).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <div class="d-grid gap-2 d-md-flex align-items-center justify-content-md-between">
      <%= link_to "Show all", jobs_path, class: "btn btn-outline-secondary" %>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render "form", job: @job %>

app/views/jobs/index.html.erb
<div class="d-grid gap-2 d-md-flex align-items-center justify-content-md-between">
  <h1>Jobs</h1>
  <%= link_to "New Job", new_job_path, class: "btn btn-outline-success" %>
</div>
<div class="row">
  <div class="table-responsive">
    <table class="table caption-top">
      <caption>List of jobs</caption>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Job title</th>
          <th scope="col">Company name</th>
          <th scope="col">Salary</th>
          <th scope="col">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each_with_index do |job, index| %>
        <tr>
          <th scope="row"><%= index+1 %></th>
          <td><%= job.title %></td>
          <td><%= job.company %></td>
          <td><%= number_to_currency(job.salary, unit: "฿", precision: 0) %></td>
          <td width="15%">
            <%= link_to "Show", job_path(job.id), class: "btn btn-outline-primary" %>
            <%= link_to "Edit", edit_job_path(job.id), class: "btn btn-outline-warning" %>
            <%= link_to "Del", job_path(job.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
          </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render "form", job: @job %>

app/views/jobs/show.html.erb
<figure class="figure">
  <blockquote class="blockquote">
    <h2 class="display-6"><%= @job.title %></h2>
    <h5><small>Company:</small> <b><span class="text-primary"><%= @job.company %></span></b></h5>
    <p>Salary: <span class="text-success"><%= number_to_currency(@job.salary, unit: "฿", precision: 0) %></span></p>
  </blockquote>
</figure>

<div class="mb-3">
  <div class="d-grid gap-2 d-md-flex align-items-center justify-content-md-between">
    <%= link_to "Show all", jobs_path, class: "btn btn-outline-secondary" %>
    <div>
      <%= link_to "Edit", edit_job_path(@job), class: "btn btn-outline-warning" %>
      <%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cotactic Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</html>